### ISSUE TITLE
Undefined variable

### ISSUE THREAD

**Issue by ads103** [libbitcoin/libbitcoin-server#17]
When attempting to compile on Ubuntu 14.04 using GCC 4.8.2, I'm receiving an error that says, "src/service/compat.hpp:10:50: error: 'incoming_message' does not name a type." With this type not being defined, compiling fails.
