### ISSUE TITLE
Signed build has link to system lib not found on 10.9 (Mavericks)

### ISSUE THREAD

**Issue by evoskuil** [libbitcoin/libbitcoin-server#83]
```
dyld: Symbol not found: _fchmodat
Referenced from: /usr/local/bin/bs
Expected in: /usr/lib/libSystem.B.dylib
in /usr/local/bin/bs
Trace/BPT trap: 5 
```
Works in 10.10 (Yosemite).
```sh
$ otool -L bs
bs:
	/opt/local/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
```

**Comment by evoskuil** [comment]
The function `_fcmodat` is only referenced from boost filesystem [here](https://github.com/boostorg/filesystem/blob/svn-branches/maintenance/1_54_0/src/operations.cpp#L1398)

**Comment by evoskuil** [comment]
Good explanation of the problem and affected environments [here](https://github.com/NixOS/nix/issues/465)
